
spring:
  main:
    jvmArguments: -Djava.security.egd=file:/dev/urandom
  datasource:
    url: jdbc:mysql://localhost:3306/golab
    username: 

    password: 

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 
            client-secret: 
            scope: 
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
        provider:
          kakao:
            authorization-uri: 
            token-uri: 
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  secret:
  expiration: 

frontend:
  url:
server:
  servlet:
    session:
      timeout: 30m
